%global tl_name hyphen-base
%global tl_revision 78076

Name:		texlive-%{tl_name}
Version:	%{tl_revision}
Release:	1
Summary:	core hyphenation support files
Group:		Publishing
URL:		https://www.ctan.org/pkg/hyphen-base
License:	LPPL
Source0:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/hyphen-base.r%{tl_revision}.tar.xz
BuildArch:	noarch
BuildSystem:	texlive
Provides:	texlive(%{tl_name}) = %{tl_revision}

%description
Includes Knuth's original hyphen.tex, zerohyph.tex to disable
hyphenation, language.us which starts the autogenerated files
language.dat and language.def (and default versions of those), etc.

