Name:		texlive-hyphen-base
Version:	74125
Release:	1
Summary:	TeXLive hyphen-base package
Group:		Publishing
URL:		https://tug.org/texlive
License:	http://www.tug.org/texlive/LICENSE.TL
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/hyphen-base.r%{version}.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg
Requires(post):	texlive-kpathsea
# FIXME we probably shouldn't require all the languages, but
# lots of stuff (like files generated by texinfo) fails because
# it tries to include everything listed in language.dat
Requires:	texlive-hyphen-afrikaans
Requires:	texlive-hyphen-ancientgreek
Requires:	texlive-hyphen-armenian
Requires:	texlive-hyphen-basque
Requires:	texlive-hyphen-belarusian
Requires:	texlive-hyphen-bulgarian
Requires:	texlive-hyphen-catalan
Requires:	texlive-hyphen-chinese
Requires:	texlive-hyphen-churchslavonic
Requires:	texlive-hyphen-coptic
Requires:	texlive-hyphen-croatian
Requires:	texlive-hyphen-czech
Requires:	texlive-hyphen-danish
Requires:	texlive-hyphen-dutch
Requires:	texlive-hyphen-english
Requires:	texlive-hyphen-esperanto
Requires:	texlive-hyphen-estonian
Requires:	texlive-hyphen-ethiopic
Requires:	texlive-hyphen-finnish
Requires:	texlive-hyphen-french
Requires:	texlive-hyphen-friulan
Requires:	texlive-hyphen-galician
Requires:	texlive-hyphen-georgian
Requires:	texlive-hyphen-german
Requires:	texlive-hyphen-greek
Requires:	texlive-hyphen-hungarian
Requires:	texlive-hyphen-icelandic
Requires:	texlive-hyphen-indic
Requires:	texlive-hyphen-indonesian
Requires:	texlive-hyphen-interlingua
Requires:	texlive-hyphen-irish
Requires:	texlive-hyphen-italian
Requires:	texlive-hyphen-kurmanji
Requires:	texlive-hyphen-latin
Requires:	texlive-hyphen-latvian
Requires:	texlive-hyphen-lithuanian
Requires:	texlive-hyphen-macedonian
Requires:	texlive-hyphen-mongolian
Requires:	texlive-hyphen-norwegian
Requires:	texlive-hyphen-occitan
Requires:	texlive-hyphen-piedmontese
Requires:	texlive-hyphen-polish
Requires:	texlive-hyphen-portuguese
Requires:	texlive-hyphen-romanian
Requires:	texlive-hyphen-romansh
Requires:	texlive-hyphen-russian
Requires:	texlive-hyphen-sanskrit
Requires:	texlive-hyphen-serbian
Requires:	texlive-hyphen-slovak
Requires:	texlive-hyphen-slovenian
Requires:	texlive-hyphen-spanish
Requires:	texlive-hyphen-swedish
Requires:	texlive-hyphen-thai
Requires:	texlive-hyphen-turkish
Requires:	texlive-hyphen-turkmen
Requires:	texlive-hyphen-ukrainian
Requires:	texlive-hyphen-uppersorbian
Requires:	texlive-hyphen-welsh

%description
TeXLive hyphen-base package.

%post
%{_sbindir}/texlive.post

%postun
if [ $1 -eq 0 ]; then
	%{_sbindir}/texlive.post
fi

#-----------------------------------------------------------------------
%files
%{_texmfdistdir}/tex/generic/config/language.dat
%{_texmfdistdir}/tex/generic/config/language.dat.lua
%{_texmfdistdir}/tex/generic/config/language.def
%{_texmfdistdir}/tex/generic/config/language.us
%{_texmfdistdir}/tex/generic/config/language.us.def
%{_texmfdistdir}/tex/generic/config/language.us.lua
%{_texmfdistdir}/tex/generic/hyphen/dumyhyph.tex
%{_texmfdistdir}/tex/generic/hyphen/hyphen.tex
%{_texmfdistdir}/tex/generic/hyphen/hypht1.tex
%{_texmfdistdir}/tex/generic/hyphen/zerohyph.tex

#-----------------------------------------------------------------------
%prep
%autosetup -p1 -c

%build

%install
mkdir -p %{buildroot}%{_texmfdistdir}
cp -fpar tex %{buildroot}%{_texmfdistdir}
